# fly.toml app configuration file generated for cadcascade on 2023-08-25T01:06:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cadcascade"
primary_region = "fra"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
